[package]

name = "gio-2_0-sys"
version = "0.0.1-dev"
authors = ["Mikhail Zabaluev <mikhail.zabaluev@gmail.com>"]
license = "LGPL-2.1+"

links = "gio-2.0"

build = "build.rs"

[build-dependencies]
pkg-config = "0.3"

[dependencies]
gtypes = "0.1"
glib-2_0-sys = "0.2"
gobject-2_0-sys = "0.2"
