[package]

name = "grust-GObject-2_0"
version = "0.0.1-dev"
authors = ["Mikhail Zabaluev <mikhail.zabaluev@gmail.com"]
license = "LGPL-2.1+"

[lib]
name = "grust_gobject_2_0"
path = "gobject.rs"

[dependencies]
gobject-2_0-sys = "0.1.0"

[dependencies.grust]
git = "https://github.com/gi-rust/grust.git"
branch = "stable"

[dependencies.grust-GLib-2_0]
path = "../glib"
